### ISSUE TITLE
Deauth not working properly

### ISSUE THREAD

**Issue by ob45** [FluxionNetwork/fluxion#1208]
#### Summary
When using any Deauting method within the fluxion script, it either struggles really hard and barely makes it or it just flat out fails to deauth devices in the network. The console will show that a deauth is in progress but all devices remain operational.
This however is not the case when I use aireplay manually.

##### What is the current behaviour?
The script manages to deauth devices **after a very long time** and **not consistently** when using the "Capture Handshake" attack.
It does **not at all** deauth devices while using the evil twin attack.
Even if I specify that a second, separate adapter should do the target tracking and deauth.

##### If the current behaviour is a bug, please provide the steps to reproduce it.
I've used VMware & VirtualBox to connect the following Wifi adapter chipsets to the VM:

- AR9271
- MT7610U
- RT5572

All of these devices support monitor and AP mode according to the [airgeddon github page](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets)

Then I started the script normally, installed all the dependencies (via the parameter -i) and started the attacks. Handshake deauth works somewhat but evil twin attack deauth doesn't work... even with a second adapter as the deauth. 

Only way I can get it to work is to let one adapter get used by fluxion and use another one to deauth the devices manually.....

Tested with: Kali 2024.3, Kali 2022.4 with all updates.
VirtualBox: v7.1.4
VmWare Pro: v17.6.1

##### What do you think the expected behaviour should be?
It should start deauthing all devices from the target network and host the AP on the same Adapter. Or at least deauth with one adapter and host the twin network on a second one.

But the deauth should work.

##### Specs

```
#### FLUXION Info
FLUXION V6.12


#### BASH Info 
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** ath9k_htc
**Chipset:** Qualcomm Atheros Communications AR9271 802.11n
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(395)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.10
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2022, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.7  - (C) 2006-2022 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                             

#### System Info
**Chipset:** Linux version 6.11.2-amd64 (devel@kali.org) (x86_64-linux-gnu-gcc-14 (Debian 14.2.0-6) 14.2.0, GNU ld (GNU Binutils for Debian) 2.43.1) #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15)

#### Chipset
Chipset: ath9k_htc
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information


##########################################################################################################################


#### FLUXION Info
FLUXION V6.12


#### BASH Info 
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan1) Info 
**Device**: phy1
**Driver:** mt76x0u
**Chipset:** Ralink Technology, Corp. MT7610U ("Archer T2U" 2.4G+5G WLAN Adapter
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(395)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.10
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2022, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.7  - (C) 2006-2022 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                             

#### System Info
**Chipset:** Linux version 6.11.2-amd64 (devel@kali.org) (x86_64-linux-gnu-gcc-14 (Debian 14.2.0-6) 14.2.0, GNU ld (GNU Binutils for Debian) 2.43.1) #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15)

#### Chipset
Chipset: mt76x0u
Chipset is not in list


#########################################################################################################################################################################################

#### FLUXION Info
FLUXION V6.12


#### BASH Info 
GNU bash, version 5.2.32(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**Path:** /usr/bin/bash


#### Interface (wlan0) Info 
**Device**: phy0
**Driver:** rt2800usb
**Chipset:** Ralink Technology, Corp. RT5572
**Master Modes** Yes
**Injection Test:** Injection is working!


#### XTerm Infos
**Version:** XTerm(395)
**Path:** /usr/bin/xterm
Test: XServer/XTerm success!


#### HostAPD Info
hostapd v2.10
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2022, Jouni Malinen <j@w1.fi> and contributors
Path: /usr/sbin/hostapd


#### Aircrack-ng Info

  Aircrack-ng 1.7  - (C) 2006-2022 Thomas d'Otreppe
  https://www.aircrack-ng.org


#### Pyrit Info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named scapy
./diagnostics.sh: line 89: pyrit: command not found
**Scapy Version:** 
Warning: Pyrit has been reported to be incompatible with scapy version 2.4.0 and above. Consult the wiki for further information. This should not affect you, if you don't choose to use pyrit in the script.                                                                                                                           

#### System Info
**Chipset:** Linux version 6.11.2-amd64 (devel@kali.org) (x86_64-linux-gnu-gcc-14 (Debian 14.2.0-6) 14.2.0, GNU ld (GNU Binutils for Debian) 2.43.1) #1 SMP PREEMPT_DYNAMIC Kali 6.11.2-1kali1 (2024-10-15)

#### Chipset
Chipset: rt2800usb
Chipset support ap mode
Chipset support monitor mode
Don't reseve all required information

```

#### Additional Info
I've used the older predecessor of Fluxion - Linset - around 2014 and can say it worked well with the AR9271 Adapter. So just to test that my adapter isn't somehow bugged I started an old VM with linset installed and was able to start the attack including deauthing all devices on the target network instantly.

So it can't be an Adapter issue.

If any more information is needed, I'm happy to provide it!

**Comment by ob45** [comment]
> Hi! I have the same situation with ar9271 and TP-Link 722. Did you find any solution to this problem? With old Kali and app versions it worked correctly. But now...don't have any ideas...

Hi there!

Unfortunately not. But what I did is use the old version of a distro, which had everything installed and configured. 
It is called "Wifislax" and has the older Version of Fluxion installed which is called "Linset".

There it worked fine, I have no idea what they did to break it here...

**Comment by SergeyBocharov89** [comment]
> Hi there!
> 
> Unfortunately not. But what I did is use the old version of a distro, which had everything installed and configured.
> It is called "Wifislax" and has the older Version of Fluxion installed which is called "Linset".
> 
> There it worked fine, I have no idea what they did to break it here...

**Comment by SergeyBocharov89** [comment]
Thanks a lot for answer ;)

**Comment by cjb900** [comment]
This isn't an issue where someone updated fluxion and it broke. It's an issue where newer version of the Linux kernel 6.1 and above break Wi-Fi cards to where VIF (what lets a wifi card split into 2 virtual interfaces, one for deauthing and one for the fake AP) does not work. You can see this referenced here https://bugzilla.kernel.org/show_bug.cgi?id=218763. You need to use a Linux kernel 6.1 or older until this issue gets fixed.

**Comment by ob45** [comment]
> This isn't an issue where someone updated fluxion and it broke. It's an issue where newer version of the Linux kernel 6.1 and above break Wi-Fi cards to where VIF (what lets a wifi card split into 2 virtual interfaces, one for deauthing and one for the fake AP) does not work. You can see this referenced here https://bugzilla.kernel.org/show_bug.cgi?id=218763. You need to use a Linux kernel 6.1 or older until this issue gets fixed.

This is definitely false because I tested this on kali 2019 to 2024 and on none of these installation fluxion was able to run the attack.
According the the release history the 2020 for example is Kernel 5.9
https://www.kali.org/releases/#:~:text=2020.4

So there is something wrong with the script as well I assume.

**Comment by strasharo** [comment]
This matches a real bug in mdk4's auto-mode deauth: mdk4's `d` mode only sends deauth/disassoc frames once it observes live data traffic from a client — until then it stays completely silent, which explains why it can "barely make it or flat out fail" while manual `aireplay-ng` (which broadcasts unconditionally) works fine on the same hardware.

Opened a fix in #1250 that adds a `--deauth-method <mdk4|aireplay-ng>` flag and defaults auto mode to aireplay-ng until this is addressed upstream in mdk4. It also switches mdk4 to target the client directly (`-B <mac>`) instead of via a blacklist file, for when you opt back into it. Would appreciate it if you could test against your AR9271/MT7610U/RT5572 setups once it's merged.
